### ISSUE TITLE
请问如何实现对一个方法的拦截即在@AtEnter的时候Mock一个返回值就返回了 不执行原有逻辑

### ISSUE THREAD

**Issue by lwsbox** [alibaba/bytekit#1]
RT

**Comment by lwsbox** [comment]
如果使用invokeOrigin  不是很灵活

**Comment by hengyunabc** [comment]
目前不支持，后续可以用 `@Instrument`的方式来实现。

**Comment by lwsbox** [comment]
后续大概是什么时候  未来可期否 👍

**Comment by hengyunabc** [comment]
目前有一个 dubbo的demo，可以参考下： https://github.com/alibaba/one-java-agent/blob/master/dubbo-test-instrument/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java
