### ISSUE TITLE
invokeOrigin 技术具体的使用demo

### ISSUE THREAD

**Issue by KylinShinlyLin** [alibaba/bytekit#6]
请问有invokeOrigin 技术的具体使用demo吗？感觉这块介绍的不是特别多

**Comment by hengyunabc** [comment]
可以看下测试代码，或者 https://github.com/alibaba/one-java-agent 里面的示例插件。 目前的确没有做到开箱即用，API层待优化。

**Comment by KylinShinlyLin** [comment]
感谢
