### ISSUE TITLE
@Binding.Method 问题

### ISSUE THREAD

**Issue by KylinShinlyLin** [alibaba/bytekit#9]
发现 @Binding.Method 注解没有正常生效，这个绑定是否已经可以使用呢？

**Comment by hengyunabc** [comment]
已修复。不过不建议使用这个 binding，因为每次实际上都是反射获取到的。建议自己绑定 class ,method name ， method desc等，自己来获取，然后缓存反射结果。因为反射的开销是比较大的。

**Comment by KylinShinlyLin** [comment]
好的，感谢
